### PR TITLE
Work around for tar being killed by OOMK

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by shr-project** [comment]
@Tofee @Herrie82 : I will update the recipe to deploy ui-print-wrapper.sh when bumping SRCREV.

**Comment by Tofee** [comment]
Ok, thanks !

**Comment by shr-project** [comment]
Something is not right, now I got sh: : unknown operand again
`
sideload-host file size 654789183 block size 65536              
Installing zip file '/sideload/package.zip'                                                     
I:Update binary zip                                                                                   
Verifying package compatibility...                                                                             
Package doesn't contain compatibility.zip entry                  
I:Zip does not contain SELinux file_contexts file in its root.                                   
I:has_legacy_properties: Found legacy property match!                                            
I:Legacy property environment initialized.                                                       
about to run program [/sbin/mount] with 2 args                                                   
                                                                                                 
Welcome to the LuneOS RootFS Updater                                                             
                                                                                                            
Mounting system and userdata partitions...                                                                       
mount: mounting /dev/block/bootdevice/by-name/system_a on /system failed: Device or resource busy
run_program: child exited with status 255                                           
about to run program [/sbin/mount] with 2 args                                        
mount: mounting /dev/block/dm-0 on /data failed: Device or resource busy                                                                                                                                                                            
run_program: child exited with status 255                                           
Copying the LuneOS rootfs tarball...                                                
about to run program [/tmp/ui-print-wrapper.sh] with 2 args                         
Deploying LuneOS...                                                                    
sh: : unknown operand                                                                  
Cleaning up left over artifacts ...                                                 
sh: : unknown operand                                                                                         
Deploying LuneOS ...                                                                                          
sh: : unknown operand                                                                                         
Extracting /data/webos-rootfs.tar.gz to /data/luneos_tmp_extract                                                                                                                                                                                    
I:TWFunc::Set_Brightness: Setting brightness control to 5                                                     
I:TWFunc::Set_Brightness: Setting brightness control to 0                                                     
Killed                                                                                                        
sh: : unknown operand                                                                                         
ERROR: Failed to extract LuneOS on the internal memory. Propably not enough free space left to install LuneOS?
sh: : unknown operand                                                                                    
Trying with busybox already unpacked from webos-rootfs (hopefully)
I:TWFunc::Set_Brightness: Setting brightness control to 150             
sh: : unknown operand                                                     
Removing /data/webos-rootfs.tar.gz                                  
sh: : unknown operand                                                                
Moving /data/luneos_tmp_extract to /data/luneos                        
sh: : unknown operand                                     
Adding /data/halium-rootfs symlink to /data/luneos              
sh: : unknown operand                                     
Done with deploying LuneOS!!!                                             
Flashing kernel ...                                                             
about to run program [/sbin/sync] with 1 args                                                                  
script result was [Installation completed, please reboot!]                                
`

**Comment by shr-project** [comment]
Works as expected now, the output before was with modified webos_deploy.sh from my previous tests

``
Installing zip file '/sideload/package.zip'                                                                    
I:Update binary zip                                                                                            
Verifying package compatibility...                                                                             
Package doesn't contain compatibility.zip entry                                                                
I:Zip does not contain SELinux file_contexts file in its root.                                                 
I:has_legacy_properties: Found legacy property match!                                                          
I:Legacy property environment initialized.                                                                     
                                                                                                               
about to run program [/sbin/mount] with 2 args                                                                 
Welcome to the LuneOS RootFS Updater                                                                                                                                                                                                                
                                                                                                               
Mounting system and userdata partitions...                                                                     
about to run program [/sbin/mount] with 2 args                                                                 
mount: mounting /dev/block/dm-0 on /data failed: Device or resource busy                                       
run_program: child exited with status 255                                                                      
Copying the LuneOS rootfs tarball...                                                                           
about to run program [/tmp/ui-print-wrapper.sh] with 2 args                                                    
Deploying LuneOS...                                                                                            
Cleaning up left over artifacts ...                                                                            
Deploying LuneOS ...                                                                                           
Extracting /data/webos-rootfs.tar.gz to /data/luneos_tmp_extract                                               
I:TWFunc::Set_Brightness: Setting brightness control to 5                                                      
I:TWFunc::Set_Brightness: Setting brightness control to 0               
Killed                                                                  
ERROR: Failed to extract LuneOS on the internal memory. Propably not enough free space left to install LuneOS?
Trying with busybox already unpacked from webos-rootfs (hopefully)                                            
Removing /data/webos-rootfs.tar.gz                                                                            
Removing old /data/luneos                                                                                      
Moving /data/luneos_tmp_extract to /data/luneos                                                               
Adding /data/halium-rootfs symlink to /data/luneos                                                            
Done with deploying LuneOS!!!                                                                                 
Flashing kernel ...                                                                                           
about to run program [/sbin/sync] with 1 args                                                                 
script result was [Installation completed, please reboot!]                                                     
Installation completed, please reboot!                                                                        
I:Updater process ended with RC=0                                                                             
``

**Comment by Tofee** [comment]
lgtm

**Pull request merged**
